INSERT INTO AGERESTRICTION
VALUES('NR', 0);

INSERT INTO AGERESTRICTION
VALUES( 'PG', 0);

INSERT INTO AGERESTRICTION
VALUES('G', 0);

INSERT INTO AGERESTRICTION
VALUES('PG13', 13);

INSERT INTO AGERESTRICTION
VALUES('14A', 14);

INSERT INTO AGERESTRICTION
VALUES('R', 18);

INSERT INTO AGERESTRICTION
VALUES('18A', 18);