INSERT INTO MOVIEISOFGENRE
VALUES(1, 'COMEDY');

INSERT INTO MOVIEISOFGENRE
VALUES(1, 'ROMANCE');

INSERT INTO MOVIEISOFGENRE
VALUES(2, 'COMEDY');

INSERT INTO MOVIEISOFGENRE
VALUES(2, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(0, 'SCI-FI');

INSERT INTO MOVIEISOFGENRE
VALUES(0, 'ADVENTURE');

INSERT INTO MOVIEISOFGENRE
VALUES(0, 'ACTION');

INSERT INTO MOVIEISOFGENRE
VALUES(3, 'COMEDY');

INSERT INTO MOVIEISOFGENRE
VALUES(3, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(4, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(4, 'COMEDY');

INSERT INTO MOVIEISOFGENRE
VALUES(4, 'CRIME');

INSERT INTO MOVIEISOFGENRE
VALUES(5, 'DOCUMENTARY');

INSERT INTO MOVIEISOFGENRE
VALUES(6, 'FAMILY');

INSERT INTO MOVIEISOFGENRE
VALUES(7, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(8, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(9, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(9, 'CRIME');

INSERT INTO MOVIEISOFGENRE
VALUES(10, 'COMEDY');

INSERT INTO MOVIEISOFGENRE
VALUES(11, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(12, 'DRAMA');

INSERT INTO MOVIEISOFGENRE
VALUES(12, 'CRIME');

INSERT INTO MOVIEISOFGENRE
VALUES(13, 'ACTION');

INSERT INTO MOVIEISOFGENRE
VALUES(13, 'ADVENTURE');

INSERT INTO MOVIEISOFGENRE
VALUES(14, 'FAMILY');

INSERT INTO MOVIEISOFGENRE
VALUES(14, 'COMEDY');

INSERT INTO MOVIEISOFGENRE
VALUES(15, 'DOCUMENTARY');

INSERT INTO MOVIEISOFGENRE
VALUES(16, 'DOCUMENTARY');
