INSERT INTO PLANTYPE
VALUES(0, 'TRIAL', 0);

INSERT INTO PLANTYPE
VALUES(1, 'BASIC', 10);

INSERT INTO PLANTYPE
VALUES(2, 'BASICPLUS', 20);

INSERT INTO PLANTYPE
VALUES(3, 'PREMIUM', 30);

INSERT INTO PLANTYPE
VALUES(4, 'PREMIUMHD', 40);
