DROP TABLE AGERESTRICTION CASCADE CONSTRAINTS;
DROP TABLE GENRE CASCADE CONSTRAINTS;
DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE MOVIEISOFGENRE CASCADE CONSTRAINTS;
DROP TABLE PAYMENTINFO  CASCADE CONSTRAINTS;
DROP TABLE PLANTYPE CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE PROFILE CASCADE CONSTRAINTS;
DROP TABLE WATCHES CASCADE CONSTRAINTS;



CREATE TABLE AGERESTRICTION(
    NAME VARCHAR(10) PRIMARY KEY,
    MINAGE  INT DEFAULT 0
    )
    
    
CREATE TABLE GENRE(
    NAME VARCHAR(30) PRIMARY KEY);
    
CREATE TABLE MOVIE(
    ID  INT PRIMARY KEY,
    TITLE VARCHAR(30) NOT NULL,
    DURATION INT,
    AGERESTRICTION VARCHAR(10),
    RELEASEYEAR INT,
    FOREIGN KEY (AGERESTRICTION) REFERENCES AGERESTRICTION(NAME)
    );
    
CREATE TABLE MOVIEISOFGENRE(
    MOVIEID INT,
    GENRE   VARCHAR(30),
    PRIMARY KEY(MOVIEID,GENRE),
    FOREIGN KEY (MOVIEID) REFERENCES MOVIE(ID),
    FOREIGN KEY (GENRE) REFERENCES GENRE(NAME)
    );
    
CREATE TABLE PAYMENTINFO(
    ID INT PRIMARY KEY,
    CARDNAME VARCHAR(30) NOT NULL,
    CARDNO VARCHAR(30) NOT NULL,
    EXPMONTH INT NOT NULL,
    EXPYEAR INT NOT NULL,
    BILLINGADDRESS VARCHAR(50) NOT NULL
    );
    
CREATE TABLE PLANTYPE(
    ID  INT PRIMARY KEY,
    NAME VARCHAR(20) UNIQUE,
    MONTHLYPAYMENT INT DEFAULT 0
    );
    
CREATE TABLE ADMIN(
    ID INT NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    PLANID INT DEFAULT 0,
    PAYMENTID INT,
    FOREIGN KEY (PLANID) REFERENCES PLANTYPE(ID)
    ON DELETE SET NULL,
    FOREIGN KEY ("PAYMENTID") REFERENCES PAYMENTINFO("ID")
    ON DELETE SET NULL
    );
    
CREATE TABLE PROFILE(
    NAME VARCHAR(30), 
    ADMINID INT,
    AGE INT DEFAULT 100,
    PRIMARY KEY(NAME, ADMINID),
    FOREIGN KEY (ADMINID) REFERENCES ADMIN(ID)
    );
    
CREATE TABLE WATCHES(
    MOVIEID INT,
    ADMINID INT,
    PROFILENAME VARCHAR(30),
    TIMEIN  INT DEFAULT 0,
    PRIMARY KEY(MOVIEID, ADMINID, PROFILENAME),
    FOREIGN KEY (MOVIEID) REFERENCES MOVIE(ID),
    FOREIGN KEY (PROFILENAME, ADMINID) REFERENCES PROFILE(NAME, ADMINID)
    );
