export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const CUSTOMER_VERIFY_SUCCESS = "CUSTOMER_VERIFY_SUCCESS";
export const CHECK_BOX_TOGGLED = "CHECK_BOX_TOGGLED";
export const CUSTOMER_DATA_SET = "CUSTOMER_DATA_SET";
