export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const CUSTOMER_VERIFY_SUCCESS = "CUSTOMER_VERIFY_SUCCESS";
export const CHECK_BOX_TOGGLED = "CHECK_BOX_TOGGLED";
export const CUSTOMER_DATA_SET = "CUSTOMER_DATA_SET";


export const PROFILES_RETRIEVE_SUCCESS = "USER_PROFILE_LIST_RETRIEVED";
export const PROFILES_RETRIEVE_FAILURE = "PROFILES_RETRIEVE_FAILURE";
export const PROFILE_SELECTED = "PROFILE_SELECTED";

export const PROFILE_CREATE_FAILURE = "PROFILE_CREATE_FAILURE";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_UPDATE_FAILURE = "PROFILE_UPDATE_FAILURE";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_DELETE_FAILURE = "PROFILE_DELETE_FAILURE";
export const PROFILE_DELETE_SUCCESS = "PROFILE_DELETE_SUCCESS";